package com.solutiondesign.skills.domain;

// Generated Feb 28, 2013 11:04:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Skillgroup generated by hbm2java
 */
@Entity
@Table(name="Skillgroup")
public class Skillgroup implements java.io.Serializable {

	private Integer skillGroupId;
	private String skillGroupName;
	private boolean isActive;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private String createdBy;
	private Date createDate;
//	private Set skills = new HashSet(0);

	public Skillgroup() {
	}

	public Skillgroup(String skillGroupName, boolean isActive,
			String lastModifiedBy, Date lastModifiedDate, String createdBy,
			Date createDate) {
		this.skillGroupName = skillGroupName;
		this.isActive = isActive;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.createdBy = createdBy;
		this.createDate = createDate;
	}

//	public Skillgroup(String skillGroupName, boolean isActive,
//			String lastModifiedBy, Date lastModifiedDate, String createdBy,
//			Date createDate, Set skills) {
//		this.skillGroupName = skillGroupName;
//		this.isActive = isActive;
//		this.lastModifiedBy = lastModifiedBy;
//		this.lastModifiedDate = lastModifiedDate;
//		this.createdBy = createdBy;
//		this.createDate = createDate;
//		this.skills = skills;
//	}

	@Id
	@GeneratedValue
	@Column(name="SkillGroupID")
	public Integer getSkillGroupId() {
		return this.skillGroupId;
	}

	public void setSkillGroupId(Integer skillGroupId) {
		this.skillGroupId = skillGroupId;
	}

	@Column(name="SkillGroupName")
	public String getSkillGroupName() {
		return this.skillGroupName;
	}

	public void setSkillGroupName(String skillGroupName) {
		this.skillGroupName = skillGroupName;
	}

	@Column(name="IsActive")
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name="LastModifiedBy")
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name="LastModifiedDate")
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name="CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name="CreateDate")
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

//	public Set getSkills() {
//		return this.skills;
//	}
//
//	public void setSkills(Set skills) {
//		this.skills = skills;
//	}

}
